apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: tekton-chains
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
data:
  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.storage: grafeas
  artifacts.pipelinerun.signer: kms
  signers.kms.kmsref: gcpkms://projects/jagathprakash-test/locations/us/keyRings/pj-keyring/cryptoKeys/pj-key/cryptoKeyVersions/1
  storage.grafeas.projectid: jagathprakash-test
  storage.grafeas.noteid: slsa-demo-note
  builder.id: $BUILDER_ID
  artifacts.taskrun.storage: "" # disabled
  artifacts.oci.storage: "" # disabled