apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  serviceAccountName: jp-tk-ksa
  pipelineSpec:
    params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    workspaces:
    - name: shared-data
    tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data
      params:
      - name: IMAGE
        value: $(params.image-reference)
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Mi
  podTemplate:
    # See https://github.com/tektoncd/catalog/issues/1044
    securityContext:
      fsGroup: 65532
  params:
  - name: repo-url
    value: https://github.com/bendory/mini-true.git
  - name: image-reference
    value: us-docker.pkg.dev/jagathprakash-test/jp-tk-repo/tekton-slsa-demo